Feature/no dist folder
fingerprintjs/cloudflare-worker-proxy pull request #118
Opened 2023-03-27 10:16 UTC by Orkuncakilkaya

2023-03-27 16:59 UTC, ilfa approved these changes

2023-03-28 08:14 UTC, necipallef requested changes

2023-03-28 08:14 UTC, necipallef commented on .github/workflows/coverage-pr.yml
> +        run: yarn build
why do we need this 2nd `yarn build` here? @Orkuncakilkaya

2023-03-28 08:14 UTC, necipallef commented on .github/workflows/release.yml
>          run: yarn version --${{ github.event.inputs.version_bump }}
`yarn version` should run before `yarn build` because the esm.js file has a comment on top stating the version of the script. @Orkuncakilkaya

2023-03-28 09:06 UTC, ilfa commented on .github/workflows/coverage-pr.yml
> +        run: yarn build
`ArtiomTr/jest-coverage-report-action` first build current branch, then target branch to compare coverage result and make a mess in generated files as a result.

2023-03-28 09:14 UTC, necipallef commented on .github/workflows/coverage-pr.yml
> +        run: yarn build
Got it, ty

2023-03-30 06:53 UTC, ilfa approved these changes

2023-03-30 09:05 UTC, necipallef approved these changes

2023-03-31 12:16 UTC, sshelomentsev approved these changes

2023-03-31 12:17 UTC, merged

2023-06-08 09:41 UTC, ilfa commented
:tada: This PR is included in version 1.3.0 :tada:

The release is available on [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-cloudflare-worker/releases/tag/v1.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: