feat(proxy-host-header): add proxy host header
fingerprintjs/cloudflare-worker-proxy pull request #176
Opened 2023-10-25 14:25 UTC by Orkuncakilkaya

2023-10-25 17:03 UTC, ilfa commented
Can we remove suffix list too?

2023-10-26 08:34 UTC, necipallef approved these changes, later dismissed

2023-10-26 08:41 UTC, necipallef commented
We can remove `src/utils/domain-suffix-list-reversed.json` file and `punycode` dependency.

2023-10-27 08:45 UTC, Orkuncakilkaya commented
I removed punycode & domain suffix list

2023-10-30 08:52 UTC, ilfa requested changes

2023-10-30 08:52 UTC, ilfa commented on test/utils/addProxyIntegrationHeaders.test.ts
> +    addProxyIntegrationHeaders(headers, 'https://example.com/worker/result', env)
We need to check `FPJS-Proxy-Forwarded-Host` header too

2023-10-30 08:53 UTC, necipallef submitted a review, later dismissed

2023-10-30 08:57 UTC, Orkuncakilkaya commented on test/utils/addProxyIntegrationHeaders.test.ts
> +    addProxyIntegrationHeaders(headers, 'https://example.com/worker/result', env)
Just pushed a commit for this

2023-10-30 17:22 UTC, ilfa commented on test/utils/addProxyIntegrationHeaders.test.ts
> +    expect(headers.get('FPJS-Proxy-Forwarded-Host')).toBe('example.com')
Let's add it for the next 2 tests too

2023-11-20 10:50 UTC, sshelomentsev approved these changes

2023-11-20 11:42 UTC, necipallef approved these changes

2023-11-20 13:04 UTC, ilfa approved these changes

2023-11-20 19:24 UTC, merged

2023-12-11 12:19 UTC, ilfa commented
:tada: This PR is included in version 1.5.0-rc.1 :tada:

The release is available on [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-cloudflare-worker/releases/tag/v1.5.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-12-11 14:23 UTC, ilfa commented
:tada: This PR is included in version 1.5.0-rc.1 :tada:

The release is available on [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-cloudflare-worker/releases/tag/v1.5.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-12-13 19:25 UTC, ilfa commented
:tada: This PR is included in version 1.5.0 :tada:

The release is available on [GitHub release](https://github.com/fingerprintjs/fingerprintjs-pro-cloudflare-worker/releases/tag/v1.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: