Update jest
fingerprintjs/cloudflare-worker-proxy pull request #52
Opened 2022-09-27 16:19 UTC by ilfa

2022-09-27 19:14 UTC, sshelomentsev approved these changes

2022-09-27 19:43 UTC, sshelomentsev commented on .node-version
> +18
Is it important to use exactly v18?

Currently, `wrangler` can't build worker due to different versions (wrangler's action is under node 16.x)

2022-09-27 19:45 UTC, sshelomentsev requested changes
Also, please set a base branch to `develop` according to our workflow.

2022-09-28 15:54 UTC, sshelomentsev approved these changes

2022-09-28 17:47 UTC, necipallef approved these changes

2022-09-28 17:47 UTC, merged